### ISSUE TITLE
Thursday 26-10-2023 roll call 

### ISSUE THREAD

**Issue by sammou00** [BF-BackEnd-class/home#23]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by Mileenka** [comment]
Hello :)

**Comment by PreethiTapati** [comment]
Present!

**Comment by inna9Z** [comment]
Present

**Comment by firity** [comment]
Hello

**Comment by Abdul-MalikSardalov** [comment]
hi

**Comment by ervinMamutov** [comment]
hi

**Comment by barny-ar** [comment]
Hey

**Comment by Helen-HYF** [comment]
:slightly_smiling_face:

**Comment by MMikhailova** [comment]
Hey guys!

**Comment by johnedelbi** [comment]
hello 🙂

**Comment by adel0moussa** [comment]
hello 
:star_struck:

**Comment by alexander-lopez-s** [comment]
hi
