### ISSUE TITLE
Dnyandeo: Full-stack-app

### ISSUE THREAD

**Issue by Dnyandeo33** [BF-BackEnd-class/home#26]
### Backend
Create an API for the user and product with validation and response status.
- [x] Create user and product models
- [x] Create User controller
- For Register user
- For Login user
- For Logout user
- [x] Create Product controller
- For GET product
- For POST product
- For UPDATE product
- For DELETE product

### Frontend
Create frontend application using React js.
- [x] Create navigation 
- [x] Get product from API
- [x] Create components for Login and Logout using Jwt token 
- [x] Create a form for POST and UPDATE product
- [x] Delete Product

This is my repository: https://github.com/Dnyandeo33/full-store-app

**Comment by Dnyandeo33** [comment]
I did all the tasks mentioned in Issues. but I am having some issues with my application.
- The application is not refreshing automatically
- I was not able to successfully protect the route.
- I'm having an issue with third-party cookies. because of this, I used universal-cookies library to get my cookies.

**Comment by sammou00** [comment]
The application is refreshing , but you have a problem with the front end, when i try to log in it is not working. you are using to much useEffect.
please check the front end react videos 
[React ](https://github.com/HackYourFutureBelgium/bf-component-based-design)
