### ISSUE TITLE
Thursday 02-11-2023 roll call

### ISSUE THREAD

**Issue by sammou00** [BF-BackEnd-class/home#38]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by alexander-lopez-s** [comment]
Present 🥶

**Comment by Dnyandeo33** [comment]
Good morning..

**Comment by IrynaSobetska** [comment]
Good morning

**Comment by ArseniiaDamaksina** [comment]
Good morning

**Comment by johnedelbi** [comment]
hi <html>
<body>


:parachute:
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by adel0moussa** [comment]
Good Morning 🥶

**Comment by inna9Z** [comment]
Good morning

**Comment by Navy2986** [comment]
Good morning everyone

**Comment by MMikhailova** [comment]
Good morning

**Comment by firity** [comment]
hello

**Comment by Abdul-MalikSardalov** [comment]
😁

**Comment by Mileenka** [comment]
Good morning 💮

**Comment by PreethiTapati** [comment]
good morning

**Comment by barny-ar** [comment]
Morning 🌄
