### ISSUE TITLE
Tuesday 07-11-2023 roll call 

### ISSUE THREAD

**Issue by Mileenka** [BF-BackEnd-class/home#45]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by Mileenka** [comment]
Good morning 🌷

**Comment by PreethiTapati** [comment]
good morning

**Comment by ArseniiaDamaksina** [comment]
Good morning

**Comment by MMikhailova** [comment]
Good morning  ☕

**Comment by barny-ar** [comment]
😃

**Comment by inna9Z** [comment]
Good morning

**Comment by ervinMamutov** [comment]
hi

**Comment by Helen-HYF** [comment]
Hi

**Comment by firity** [comment]
Hello

**Comment by IrynaSobetska** [comment]
Hello

**Comment by Dnyandeo33** [comment]
hello

**Comment by Abdul-MalikSardalov** [comment]
🤝

**Comment by adel0moussa** [comment]
Morning
