### ISSUE TITLE
Monday 20-11-2023 roll call 

### ISSUE THREAD

**Issue by sammou00** [BF-BackEnd-class/home#64]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by ervinMamutov** [comment]
hi

**Comment by Dnyandeo33** [comment]
good morning...

**Comment by Abdul-MalikSardalov** [comment]
☕️🥱

**Comment by MMikhailova** [comment]
Good morning ☕

**Comment by Mileenka** [comment]
Good morning 🏵️

**Comment by ArseniiaDamaksina** [comment]
food mooooorniiiiing

**Comment by inna9Z** [comment]
Good morning

**Comment by IrynaSobetska** [comment]
Good morning

**Comment by barny-ar** [comment]
Selam

**Comment by PreethiTapati** [comment]
good morning

**Comment by Navy2986** [comment]
good morning

**Comment by firity** [comment]
hello
