### ISSUE TITLE
Tuesday 28-11-2023 roll call 

### ISSUE THREAD

**Issue by Mileenka** [BF-BackEnd-class/home#80]
## Roll Call!

Leave a comment with these two things:

1. A summary of your study using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by ArseniiaDamaksina** [comment]
Good morning

**Comment by Dnyandeo33** [comment]
Good morning...

**Comment by Mileenka** [comment]
Good morning 🌹

**Comment by PreethiTapati** [comment]
good morning

**Comment by inna9Z** [comment]
Good Morning

**Comment by ervinMamutov** [comment]
hi

**Comment by MMikhailova** [comment]
Morning ☕

**Comment by IrynaSobetska** [comment]
Good morning

**Comment by barny-ar** [comment]
selam

**Comment by Navy2986** [comment]
good morning
